# Site settings
title: Life.inspect
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  www.lifeinspect.com | Life • Inspected by Shinn Chong
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lifeinspect.com" # the base hostname & protocol for your site
twitter_username: shinnchong
github_username:  shinnyx

# Build settings
markdown: kramdown

paginate: 20
paginate_path: "/page/:num/"

gems:
  - neat
  - jemoji

# Not supported by GitHub Pages yet.
# https://help.github.com/articles/page-build-failed-config-file-error/#highlighting-errors
# highlighter: rogue
highlighter: pygments
